# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kevin Santos
tagline:          'getting by'
description:      ''
url:              https://kev-santos.github.io
baseurl:          /

author:
  name:           'Kevin Santos'
  url:            https://kev-santos.github.io

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
# version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
